### ISSUE TITLE
gcc-6.4.0 missing in BinKit 2.0 dataset

### ISSUE THREAD

**Issue by seekamoon** [SoftSec-KAIST/BinKit#12]
Greetings. Thank you for your fundamental work. Now I encounter a problem, which makes me feel confused.

README points out that some binaries are compiled by gcc-6.4.0. However, after I downloaded the BinKit 2.0 dataset and checked the content, I cannot find any binaries generated by gcc-6.4.0. Is the README wrong?

**Comment by topcue** [comment]
Hi @seekamoon,

We decided to provide the pre-compiled BinKit 2.0 dataset, selecting gcc-6.4.0 and gcc-8.2.0 as minor versions of gcc-6 and gcc-8 to maintain only one major version of each compiler.

However, you can compile binaries for gcc-6.4.0 and gcc-8.5.0 using ctng_conf/6.4 and ctng_conf/8.5.

**Comment by seekamoon** [comment]
Thank you for your response. Now I see.

**Comment by seekamoon** [comment]
Thank you for your response. Now I see.
