### ISSUE TITLE
pickle  dataset 

### ISSUE THREAD

**Issue by qinzhengze** [SoftSec-KAIST/BinKit#6]
Hi， I am testing my method on BinKit, The dataset is too large， could you supply the dataset(pickle files) which extracts features already by Tiklib.

**Comment by 0xdkay** [comment]
Sure, I will upload it soon.

**Comment by qinzhengze** [comment]
thanks， I will really appreciate it.

**Comment by 0xdkay** [comment]
Sorry for the late response. I just added download urls for the pickle files (see 469bc1d).
Sadly, I recognized that the size of the pickle files is bigger than the original dataset :/
