### ISSUE TITLE
Build failed in step 'Installing C library' (gcc9 + glibc 2.31+ target x86_64)

### ISSUE THREAD

**Issue by lion10** [SoftSec-KAIST/BinKit#7]
I am trying to set up the gcc, but this issue has been raised and I reported it to crosstool-ng
https://github.com/crosstool-ng/crosstool-ng/issues/1842#issue-1423642776

Is it mandatory to use the same Glibc version which is 2.26 you mentioned in the setup_gcc.sh script?

![Screenshot from 2022-10-27 13-39-04](https://user-images.githubusercontent.com/31984164/198192835-c8f4731c-68c0-4ea3-8ed5-6fcc9e26294e.png)

Any suggestion?

**Comment by 0xdkay** [comment]
Hi @lion10 ,

The version written in the ct-ng configuration file would be the one used in the compilation environment, not your system's.

Besides, the gcc that you tried to build is v9.4, but I have tested gcc <= v8.4 (the tested versions are in the readme file).
Thus, the compilation error may come from the latest gcc's version issue co-related with the glibc version.

While compiling gcc <= v8.4, I got build errors so I switched the compilation environment's glibc version (the ct-ng configuration file) from 2.27 to 2.26, though I may not correctly remember this because it has been long ago.

**Comment by lion10** [comment]
I downgraded gcc compilier to v8.4 and tried to run the script scripts/setup_gcc.sh but with no success. we are using ubunutu 20.04 LTS and the our Glibc =2.31. we tried to edit the setup_gcc script to use glibc 2.31 but still got error. here is a sample from of the error and we hope that you can give us a specifc step to by pass this error.
<img width="379" alt="image" src="https://user-images.githubusercontent.com/31984164/201011354-b7fb71bd-0d48-4cde-b37d-f55ca5855762.png">
The full build log file for x86-64 is attached

[build.log](https://github.com/SoftSec-KAIST/BinKit/files/9977745/build.log)
 

we are looking forwared to hearing from you

**Comment by 0xdkay** [comment]
okay, let me take a look. I will check it as soon as I become available. :)

**Comment by 0xdkay** [comment]
@lion10 Just to make sure, the reason that you are trying to fix the *.conf file to use glibc 2.31 is to make sure the compiled gcc binary is based on gblic 2.31? If not, you do not need to change it leaving to use 2.26 although your host uses glibc 2.31. As I stated above, the ct-ng compilation uses a separate environment from your host.

**Comment by lion10** [comment]
@0xdkay Is it work for you without any issues?!

> okay, let me take a look. I will check it as soon as I become available. :) Currently, I'm setting up the same environment as you provided. Ubuntu 20.04.5 LTS, Glibc 2.31.

**Comment by lion10** [comment]
@0xdkay I will reinstall it again. What is the version ct-ng ?! 1.24, right? Because there is a new version 1.25 


> @lion10 Just to make sure, the reason that you are trying to fix the *.conf file to use glibc 2.31 is to make sure the compiled gcc binary is based on gblic 2.31? If not, you do not need to change it leaving to use 2.26 although your host uses glibc 2.31. As I stated above, the ct-ng compilation uses a separate environment from your host.

**Comment by 0xdkay** [comment]
I'm testing on it but need some time because my current machine is not powerful 🙃 

I will let you know as it turns out.

> @0xdkay Is it work for you without any issues?!
> 
> 
> 
> > okay, let me take a look. I will check it as soon as I become available. :) Currently, I'm setting up the same environment as you provided. Ubuntu 20.04.5 LTS, Glibc 2.31.
> 
> 
> 
>

**Comment by 0xdkay** [comment]
@lion10  I've tested on two systems and successfully compiled gcc 9.4.
1. Ubuntu 18.04.6 LTS with glibc 2.27
2. Ubuntu 20.04.5 LTS with gblic 2.31.
Here, the glibc version is the host system's glibc version, and I did not change any script or configuration files.

On the other hand, I first checkout out to crosstool-ng-1.24 (See git checkout command below in `scripts/setup-ctng.sh`).
It seems that the latest version of crosstool-ng-1.25 may not be compatible with my configuration files.

I will update the corresponding file.

```sh
#!/bin/bash
if [ -z "$TOOL_PATH" ]; then
    echo "env \$TOOL_PATH should be defined first."
    echo "source scripts/env.sh"
    exit
fi

# setup crosstool-ng
CTNG_BIN="$TOOL_PATH/crosstool-ng/ct-ng"
CTNG_PATH="$TOOL_PATH/crosstool-ng"
if [ ! -f "$CTNG_BIN" ]; then
    if [ ! -d "$CTNG_PATH" ]; then
        git clone "https://github.com/crosstool-ng/crosstool-ng" "$CTNG_PATH"
    fi
    cd "$CTNG_PATH"

    git checkout crosstool-ng-1.24.0 # <------- this is added

    make distclean

    ./bootstrap
    ./configure --enable-local
    make -j "${NUM_JOBS}" -l "${MAX_JOBS}"
fi
export CTNG_BIN
export CTNG_PATH
```

**Comment by 0xdkay** [comment]
Glad to hear that. Please let me know if you have any other issue.
